### ISSUE TITLE
Обновление оглавления

### ISSUE THREAD

**Issue by AndreevAA** [AndreevAA/beansup#2]
Обновил оглавление, куда вынес все названия с `#..`

Нужно просмотреть и при необходимость добавить или исправить.

Если все ок, то закрывай @01Flame10

**Comment by 01Flame10** [comment]
В оглавлении есть, а по факту нет "Страница установки". Все остальное присутствует.

**Comment by AndreevAA** [comment]
> В оглавлении есть, а по факту нет "Страница установки". Все остальное присутствует.

@01Flame10, скорректил, 

В оглавлении:
<img width="2048" alt="image" src="https://user-images.githubusercontent.com/58621780/105607663-24a01e80-5db1-11eb-9f5d-46e5b31da968.png">


Куда бросает:
<img width="2048" alt="image" src="https://user-images.githubusercontent.com/58621780/105607667-2d90f000-5db1-11eb-8613-9e3173e898b1.png">

**Comment by 01Flame10** [comment]
Крут, закрываю
